Importamos librerias y definimos la ruta de la base de datos

In [6]:
import os
import pandas as pd
import face_recognition
from PIL import Image
import matplotlib.pyplot as plt
import random
import numpy as np

# Definir la ruta de la carpeta que contiene las imágenes
ruta_carpeta = 'C:\\Users\\Waldosir\\Documents\\2doCodigo\\TopicoIA\\Marzo\\BD\\corpus_images'



Recorremos toda la carpeta y hacemos una matriz con todos los datos de todas las imagenes

In [24]:
# Crear una lista para almacenar los datos de las imágenes
datos_imagen_recortada = []
# Recorrer la carpeta para buscar archivos jpg
for carpeta_nombre in os.listdir(ruta_carpeta):
    carpeta_ruta = os.path.join(ruta_carpeta, carpeta_nombre)
    if os.path.isdir(carpeta_ruta):
        for archivo_nombre in os.listdir(carpeta_ruta):
            try:
                archivo_ruta = os.path.join(carpeta_ruta, archivo_nombre)
                
                # Cargar la imagen utilizando PIL (Pillow)
                imagen = face_recognition.load_image_file(archivo_ruta)
                
                # Redimensionar la imagen a 150x150
                imagen_redimensionada = np.array(Image.fromarray(imagen).resize((150, 150)))
                # Obtener los landmarks faciales
                landmarks = face_recognition.face_landmarks(imagen_redimensionada)
                
                caracteristicas = []
                for clave,valor in landmarks[0].items():
                    caracteristicas.append(valor)

                # Detectar los rostros en la imagen
                rostros = face_recognition.face_locations(imagen_redimensionada)

                #Recorta la cara
                cara = rostros[0]
                top, right, bottom, left = cara
                cara_recortada = imagen_redimensionada[top:bottom, left:right]
                
                # Agregar la información de la imagen al DataFrame
                datos_imagen_recortada.append([imagen_redimensionada, caracteristicas,cara_recortada,carpeta_nombre])
            except Exception as e:
                print("Error en archivo:"+str(archivo_nombre))

Error en archivo:225.jpeg
Error en archivo:226.jpeg
Error en archivo:228.jpeg
Error en archivo:230.jpeg
Error en archivo:234.jpeg
Error en archivo:240.jpeg
Error en archivo:241.jpeg
Error en archivo:242.jpeg
Error en archivo:243.jpeg
Error en archivo:250.jpeg
Error en archivo:251.jpeg
Error en archivo:255.jpeg
Error en archivo:256.jpeg
Error en archivo:identificador_1558_2016-11-28_14-55-22.jpeg
Error en archivo:identificador_3018_2016-11-30_11-18-55.jpeg
Error en archivo:identificador_5867_2016-12-05_15-02-28.jpeg
Error en archivo:identificador_993_2016-11-09_14-05-22.jpeg
Error en archivo:identificador_5772_2016-12-05_14-31-53.jpeg
Error en archivo:identificador_994_2016-11-09_14-05-26.jpeg


In [25]:
columnas = ['Imagen', 'Caracteristicas', 'Rostro', 'Etiqueta']
df_imagenes_recortadas = pd.DataFrame(datos_imagen_recortada, columns=columnas)
df_imagenes_recortadas.head()

Imagen  \
0  [[[165, 165, 162], [165, 166, 161], [165, 166,...   
1  [[[164, 166, 161], [165, 167, 162], [164, 166,...   
2  [[[165, 165, 163], [165, 165, 163], [164, 165,...   
3  [[[165, 166, 162], [165, 165, 163], [165, 165,...   
4  [[[165, 166, 161], [166, 167, 162], [165, 167,...   

                                     Caracteristicas  \
0  [[(62, 83), (62, 88), (62, 92), (63, 97), (64,...   
1  [[(62, 83), (62, 87), (63, 92), (63, 97), (64,...   
2  [[(63, 82), (63, 87), (63, 91), (63, 96), (65,...   
3  [[(63, 83), (63, 87), (63, 92), (63, 97), (64,...   
4  [[(63, 82), (63, 87), (63, 91), (63, 96), (65,...   

                                              Rostro Etiqueta  
0  [[[160, 162, 161], [160, 162, 161], [160, 162,...    bored  
1  [[[160, 162, 160], [161, 162, 161], [160, 161,...    bored  
2  [[[159, 161, 158], [160, 162, 159], [161, 162,...    bored  
3  [[[159, 161, 158], [161, 163, 160], [155, 157,...    bored  
4  [[[160, 162, 159], [161, 163, 161], [152, 154,...    bored

Conversion a JSON. Es muy pesado, por lo que pasamos de ello.

In [9]:
#df_imagenes_recortadas.to_json('test.csv')

In [10]:
#df_jason = pd.read_json('test.csv')
#df_jason.head()

Pickle es una buena opción. Este se usa para serializar objetos en Python. Lamentablemente su uso está únicamente destinado a Python

In [11]:
#df_imagenes_recortadas.to_pickle('test.pkl')

In [12]:
#df_pickle = pd.read_pickle('test.pkl')
#df_pickle.head()

HDF5 es una gran opción. Se usa para el manejo de datos y pueden utilizarlo otros lenguajes o programas como MATLAB y Java. Está destinado para manejo de grandes datos.

Instalar tables para usar hdf5

In [13]:
pip install tables

Note: you may need to restart the kernel to use updated packages.


In [26]:
df_imagenes_recortadas.to_hdf('testHDF.h5', key='dataframe', mode='w')

C:\Users\Waldosir\AppData\Local\Temp\ipykernel_10892\365625603.py:1: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Index(['Imagen', 'Caracteristicas', 'Rostro', 'Etiqueta'], dtype='object')]

  df_imagenes_recortadas.to_hdf('testHDF.h5', key='dataframe', mode='w')


Leer el archivo creado

In [27]:
df_imagenes_recortadas_delHDF = pd.read_hdf('testHDF.h5')


In [28]:
df_imagenes_recortadas_delHDF.head()

Imagen  \
0  [[[165, 165, 162], [165, 166, 161], [165, 166,...   
1  [[[164, 166, 161], [165, 167, 162], [164, 166,...   
2  [[[165, 165, 163], [165, 165, 163], [164, 165,...   
3  [[[165, 166, 162], [165, 165, 163], [165, 165,...   
4  [[[165, 166, 161], [166, 167, 162], [165, 167,...   

                                     Caracteristicas  \
0  [[(62, 83), (62, 88), (62, 92), (63, 97), (64,...   
1  [[(62, 83), (62, 87), (63, 92), (63, 97), (64,...   
2  [[(63, 82), (63, 87), (63, 91), (63, 96), (65,...   
3  [[(63, 83), (63, 87), (63, 92), (63, 97), (64,...   
4  [[(63, 82), (63, 87), (63, 91), (63, 96), (65,...   

                                              Rostro Etiqueta  
0  [[[160, 162, 161], [160, 162, 161], [160, 162,...    bored  
1  [[[160, 162, 160], [161, 162, 161], [160, 161,...    bored  
2  [[[159, 161, 158], [160, 162, 159], [161, 162,...    bored  
3  [[[159, 161, 158], [161, 163, 160], [155, 157,...    bored  
4  [[[160, 162, 159], [161, 163, 161], [152, 154,...    bored

Sacar muestras de una fila:

In [29]:
# Acceder a una fila específica (por ejemplo, la primera fila)
fila_seleccionada = df_imagenes_recortadas_delHDF.iloc[0]

# Extraer un dato como si fuera un array
dato = fila_seleccionada['Imagen']  # Suponiendo que deseas extraer el dato de la columna 'Imagen'

# Ahora 'dato' contiene el valor de 'Imagen' de la primera fila del DataFrame
print(dato)

[[[165 165 162]
  [165 166 161]
  [165 166 161]
  ...
  [170 169 167]
  [171 170 168]
  [170 169 167]]

 [[165 165 163]
  [166 167 162]
  [166 167 162]
  ...
  [170 169 167]
  [171 170 168]
  [171 170 168]]

 [[165 166 163]
  [166 167 164]
  [165 166 161]
  ...
  [170 169 167]
  [171 170 168]
  [171 170 168]]

 ...

 [[138 138 136]
  [138 138 136]
  [138 138 136]
  ...
  [153 152 148]
  [152 153 148]
  [152 152 150]]

 [[138 138 136]
  [138 138 136]
  [138 138 136]
  ...
  [152 153 148]
  [152 153 148]
  [152 152 149]]

 [[137 137 135]
  [137 137 135]
  [137 137 135]
  ...
  [151 152 147]
  [151 152 147]
  [151 151 149]]]


KNN

In [34]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [36]:
df = df_imagenes_recortadas_delHDF
X = df.drop('Imagen', axis=1)
X = X.drop('Etiqueta', axis=1)
y = df['Etiqueta']

In [37]:
X.head()

Caracteristicas  \
0  [[(62, 83), (62, 88), (62, 92), (63, 97), (64,...   
1  [[(62, 83), (62, 87), (63, 92), (63, 97), (64,...   
2  [[(63, 82), (63, 87), (63, 91), (63, 96), (65,...   
3  [[(63, 83), (63, 87), (63, 92), (63, 97), (64,...   
4  [[(63, 82), (63, 87), (63, 91), (63, 96), (65,...   

                                              Rostro  
0  [[[160, 162, 161], [160, 162, 161], [160, 162,...  
1  [[[160, 162, 160], [161, 162, 161], [160, 161,...  
2  [[[159, 161, 158], [160, 162, 159], [161, 162,...  
3  [[[159, 161, 158], [161, 163, 160], [155, 157,...  
4  [[[160, 162, 159], [161, 163, 161], [152, 154,...

In [33]:
y.head()

0    bored
1    bored
2    bored
3    bored
4    bored
Name: Etiqueta, dtype: object

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [60]:
X_train_numpy = X_train.values
X_test_numpy = X_test.values
X_train_reshaped = X_train_numpy.reshape(-1, 28, 28, 1).astype('float32')/255

X_train = X_train.reshape(28,28,1).astype('float32')/255
X_test = X_test.reshape(28,28,1).astype('float32')/255

AttributeError: 'DataFrame' object has no attribute 'reshape'