In [1]:
import face_recognition
from PIL import ImageDraw
import PIL.Image as Image

ruta = "C:\\Users\\Waldosir\\Documents\\2doCodigo\\TopicoIA\\Marzo\\BD\\corpus_images\\bored\\61.jpeg"

Imagen en crudo

In [7]:
imagen = face_recognition.load_image_file(ruta)
print(imagen)


[[[173 175 172]
  [173 175 172]
  [173 175 172]
  ...
  [177 175 176]
  [177 175 176]
  [177 175 176]]

 [[173 175 172]
  [173 175 172]
  [173 175 172]
  ...
  [178 176 177]
  [179 177 178]
  [179 177 178]]

 [[173 175 172]
  [173 175 172]
  [173 175 172]
  ...
  [178 178 178]
  [178 178 178]
  [178 178 178]]

 ...

 [[114  97 103]
  [119 104 109]
  [142 132 133]
  ...
  [130 132 129]
  [130 132 129]
  [129 131 128]]

 [[127 108 114]
  [141 124 130]
  [148 139 140]
  ...
  [132 132 130]
  [131 131 129]
  [131 131 129]]

 [[116  95 102]
  [141 124 130]
  [129 120 121]
  ...
  [131 131 129]
  [131 131 129]
  [131 131 129]]]


Puntos de la cara

In [6]:
face_locations = face_recognition.face_locations(imagen)
print(face_locations)

[(139, 386, 325, 201)]


Mostrar imagen recortada

In [3]:
cara = face_locations[0]
top, right, bottom, left = cara
imagen_pil = Image.open(ruta)
cara_recortada = imagen_pil.crop((left, top, right, bottom))
#cara_recortada.show()

Mostrar la imagen

In [5]:
pil_image = Image.fromarray(imagen)
pil_image.show()

In [ ]:
face_landmarks_list = face_recognition.face_landmarks(imagen)
print(face_landmarks_list)

[{'chin': [(92, 303), (98, 349), (111, 394), (123, 439), (136, 484), (159, 525), (189, 556), (226, 580), (265, 587), (302, 579), (337, 556), (365, 524), (388, 483), (403, 439), (415, 394), (427, 348), (432, 303)], 'left_eyebrow': [(122, 281), (147, 270), (173, 270), (199, 277), (224, 289)], 'right_eyebrow': [(306, 288), (331, 275), (357, 269), (383, 268), (407, 278)], 'nose_bridge': [(266, 326), (266, 359), (266, 393), (266, 426)], 'nose_tip': [(241, 442), (252, 447), (266, 452), (279, 447), (291, 442)], 'left_eye': [(154, 326), (173, 314), (196, 316), (214, 332), (193, 336), (171, 335)], 'right_eye': [(316, 330), (334, 314), (357, 312), (375, 324), (359, 333), (337, 334)], 'top_lip': [(208, 493), (230, 481), (251, 474), (267, 479), (283, 474), (301, 480), (323, 491), (312, 493), (283, 492), (266, 493), (250, 493), (219, 495)], 'bottom_lip': [(323, 491), (303, 510), (284, 520), (266, 522), (249, 521), (229, 511), (208, 493), (219, 495), (250, 494), (266, 496), (283, 493), (312, 493)]}]

In [ ]:
for(face_landmarks) in face_landmarks_list:
    print("The chin is at these pixel locations: {}".format(face_landmarks['chin']))

The chin is at these pixel locations: [(92, 303), (98, 349), (111, 394), (123, 439), (136, 484), (159, 525), (189, 556), (226, 580), (265, 587), (302, 579), (337, 556), (365, 524), (388, 483), (403, 439), (415, 394), (427, 348), (432, 303)]


In [ ]:
for clave, valor in face_landmarks_list[0].items():
    print(clave + ":", valor)

chin: [(92, 303), (98, 349), (111, 394), (123, 439), (136, 484), (159, 525), (189, 556), (226, 580), (265, 587), (302, 579), (337, 556), (365, 524), (388, 483), (403, 439), (415, 394), (427, 348), (432, 303)]
left_eyebrow: [(122, 281), (147, 270), (173, 270), (199, 277), (224, 289)]
right_eyebrow: [(306, 288), (331, 275), (357, 269), (383, 268), (407, 278)]
nose_bridge: [(266, 326), (266, 359), (266, 393), (266, 426)]
nose_tip: [(241, 442), (252, 447), (266, 452), (279, 447), (291, 442)]
left_eye: [(154, 326), (173, 314), (196, 316), (214, 332), (193, 336), (171, 335)]
right_eye: [(316, 330), (334, 314), (357, 312), (375, 324), (359, 333), (337, 334)]
top_lip: [(208, 493), (230, 481), (251, 474), (267, 479), (283, 474), (301, 480), (323, 491), (312, 493), (283, 492), (266, 493), (250, 493), (219, 495)]
bottom_lip: [(323, 491), (303, 510), (284, 520), (266, 522), (249, 521), (229, 511), (208, 493), (219, 495), (250, 494), (266, 496), (283, 493), (312, 493)]


Vamos a combinarlo para hacer un dataset. Primero las librerias

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf



In [ ]:
import os

# Ruta al directorio principal donde se descomprimieron los archivos
directorio_principal = "C:\\Users\\Waldosir\\Documents\\2doCodigo\\TopicoIA\\Marzo\\BD\\corpus_images"

# Listar directorios en el directorio principal
directorios = [nombre for nombre in os.listdir(directorio_principal) if os.path.isdir(os.path.join(directorio_principal, nombre))]

# Imprimir los directorios encontrados
print("Directorios encontrados:")
for directorio in directorios:
    print(directorio)


Directorios encontrados:
bored
engaged
excited
focused
interested
relaxed


In [ ]:

# Ruta al directorio principal donde se descomprimieron los archivos
"""
# Recorrer cada carpeta dentro del directorio principal
for carpeta in os.listdir(directorio_principal):
    carpeta_path = os.path.join(directorio_principal, carpeta)

    # Verificar si es un directorio
    if os.path.isdir(carpeta_path):
        print(f"Recorriendo imágenes en la carpeta: {carpeta}")

        # Recorrer cada archivo en la carpeta
        for archivo in os.listdir(carpeta_path):

            archivo_path = os.path.join(carpeta_path, archivo)

            # Verificar si es un archivo de imagen (puedes ajustar las extensiones según tus necesidades)
            if archivo.lower().endswith((".png", ".jpg", ".jpeg")):
                print(f"Procesando imagen: {archivo}")

                # Ejemplo de carga de imagen utilizando PIL
                #imagen = Image.open(archivo_path)
                imagen = face_recognition.load_image_file(archivo_path)
                
                # Puedes realizar operaciones con la imagen aquí, si es necesario
                face_locations = face_recognition.face_locations(imagen)
                print(face_locations)

            break;
"""
# Recuerda ajustar las rutas y extensiones de archivo según tu estructura y necesidades específicas.





'\n# Recorrer cada carpeta dentro del directorio principal\nfor carpeta in os.listdir(directorio_principal):\n    carpeta_path = os.path.join(directorio_principal, carpeta)\n\n    # Verificar si es un directorio\n    if os.path.isdir(carpeta_path):\n        print(f"Recorriendo imágenes en la carpeta: {carpeta}")\n\n        # Recorrer cada archivo en la carpeta\n        for archivo in os.listdir(carpeta_path):\n\n            archivo_path = os.path.join(carpeta_path, archivo)\n\n            # Verificar si es un archivo de imagen (puedes ajustar las extensiones según tus necesidades)\n            if archivo.lower().endswith((".png", ".jpg", ".jpeg")):\n                print(f"Procesando imagen: {archivo}")\n\n                # Ejemplo de carga de imagen utilizando PIL\n                #imagen = Image.open(archivo_path)\n                imagen = face_recognition.load_image_file(archivo_path)\n                \n                # Puedes realizar operaciones con la imagen aquí, si es necesari